[step2] 인덱스 설계
next-step/infra-subway-k8s pull request #31
Opened 2023-02-25 07:18 UTC by ifjso

- m1 에서 실행하였습니다.

2023-02-25 08:34 UTC, brainbackdoor requested changes
2단계 미션 잘 진행하셨네요~ 👍🏻 
빠트린 요구사항이 있어서 Request Changes 헀어요~ 확인 바래요~

2023-02-25 08:34 UTC, brainbackdoor commented on README.md
> +    order by null
- member 테이블에 (age, id) 결합 인덱스를 만들고 어떤 차이가 있는지, 이유를 한번 생각해보시겠어요?

2023-02-25 08:34 UTC, brainbackdoor commented on README.md
> +   1. 프로그래머별로 해당하는 병원 이름을 반환하세요.
- [Coding as a Hobby](https://insights.stackoverflow.com/survey/2018#developer-profile-_-coding-as-a-hobby) 와 같은 결과를 반환하세요.
1번 문제는 요거예요~

2023-02-25 10:26 UTC, ifjso commented on README.md
> +   1. 프로그래머별로 해당하는 병원 이름을 반환하세요.
아하 넵 추가하였습니다.
fixed 031eb09c5ca4c9dbf7d66966aa5d3bb3b82b4eab

2023-02-25 11:03 UTC, ifjso commented on README.md
> +    order by null
말씀하신 결합 인덱스를 추가하여 row 탐색이 줄어들었고, 전체 쿼리 코스트도 약 20% 감소했습니다. 
결합 인덱스로 인해 먼저 age로 정렬되고 그 다음에 id로 정렬되어, age가 효율적으로 탐색되어 전체 쿼리 코스트가 감소된 것 같습니다. 만약 id를 결합 인덱스의 첫 번째 컬럼으로 선택했다면, id는 모두 다르기 때문에 id로 정렬되어도 age는 무의미한 정렬이 되었을 것이므로, 더 비효율적인 탐색이 되었을 것입니다. 이렇게 생각하는 것이 맞을까요?

2023-02-26 16:23 UTC, brainbackdoor approved these changes
피드백 반영 확인했어요~ 👍🏻 
미션 진행하느라 고생 많으셨어요~ ㅎ.ㅎ

2023-02-26 16:23 UTC, merged